version: "3.7"
services:
    kc:
        container_name: kc
        image: quay.io/keycloak/keycloak:23.0.1
        restart: unless-stopped
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8080:8080"
        networks:
            - kc
        volumes:
            - kc_import:/opt/keycloak/data/import
        command: start-dev --import-realm
networks:
    kc:
        driver: bridge
volumes:
    kc_import:

        
